name: "Build ios example"

on:
  workflow_call:
    inputs:
      # (optional) you can specify which version of Flutter will be used for Analysis workflow, defaults to 3.10.5
      flutter-version:
        required: false
        type: string
        

jobs:
  build_ios_example:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter with exact version
        if: ${{ inputs.flutter-version != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Install Flutter from Stable branch
        if: ${{ inputs.flutter-version == ''}}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: |
          cd example
          flutter pub get
          flutter build ios --release --no-codesign
