name: Install Flutter

on:
  workflow_call:
    inputs:
      # (optional) you can specify which version of Flutter will be used, defaults is the latest release from stable channel
      FLUTTER_VERSION:
        required: false
        type: string

jobs:
  install_flutter:
    name: Install Flutter
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter with exact version
        if: ${{ inputs.FLUTTER_VERSION != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.FLUTTER_VERSION }}

      - name: Install Flutter from Stable branch
        if: ${{ inputs.FLUTTER_VERSION == ''}}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
