name: Show Me json
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        CON_STRING: ${{secrets.PUB_CREDENTIAL_JSON}}
      run: |
        echo ${{secrets.PUB_CREDENTIAL_JSON}} | sed 's/./& /g'
