name: "Run example app"

on:
  workflow_call:
    input:
      # (optional) you can specify which version of Flutter will be used for Analysis workflow, defaults to 3.10.5
      flutter-version:
        required: false
        type: string
        default: "3.10.5"

jobs:
  run_example_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{input.flutter-version}}

      - name: Install dependencies
        run: flutter pub get

      - name: Run example app
        run: dart example/lib/main.dart
