name: Run example app

on:
  workflow_call:
    inputs:
      # (optional) you can specify which version of Flutter will be used, defaults is the latest release from stable channel
      FLUTTER_VERSION:
        required: false
        type: string

jobs:
  run_example_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/workflows/install_flutter.yml
        with:
          FLUTTER_VERSION: ${{ inputs.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run example app
        run: dart example/lib/main.dart
