name: "Run example app"

on:
  workflow_call:
    inputs:
      # (optional) you can specify which version of Flutter will be used for Analysis workflow, defaults to 3.10.5
      flutter-version:
        required: false
        type: string

jobs:
  run_example_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter with exact version
        if: ${{ inputs.flutter-version != ''}}
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Install Flutter from Stable branch
        if: ${{ inputs.flutter-version == ''}}
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run example app
        run: dart example/lib/main.dart
