name: Testing

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
    inputs:
      # (optional) you can specify which version of Flutter will be used, defaults is the latest release from stable channel
      FLUTTER_VERSION:
        required: false
        type: string

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/workflows/install_flutter.yml
        with:
          FLUTTER_VERSION: ${{ inputs.FLUTTER_VERSION }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        if: ${{ success() }}
        run: |
          flutter test --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
