name: "Testing"

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true
    inputs:
      # (optional) you can specify which version of Flutter will be used for Analysis workflow, defaults to 3.10.5
      flutter-version:
        required: false
        type: string
        default: "3.10.5"
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        if: success()
        run: |
          flutter test --coverage
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info